### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by Lucretiel** [InquisitivePenguin/cascade#4]

**Comment by snowsignal** [comment]
What would those tests look like? Should we check to make sure the macro doesn't break when we make changes to it?

**Comment by Lucretiel** [comment]
Well, at the very least, add some doctest examples, which will stop succeeding if something breaks accidentally.

**Comment by snowsignal** [comment]
I forgot to close this earlier, but I've added doctests, so this issue should be resolved.
