### ISSUE TITLE
1.0 release?

### ISSUE THREAD

**Issue by Lucretiel** [InquisitivePenguin/cascade#5]
It seems like this library is in a pretty solid state. Any chance of a 1.0 release?

**Comment by snowsignal** [comment]
Yes, I've been planning on that. I've wanted to make a few more examples and polish the code prior to that though. I've been occupied with school lately, but I promise I will do a 1.0 release soon<sup>TM</sup>.

**Comment by snowsignal** [comment]
I created a milestone and a few issues that need to be completed by me before I can release 1.0. Worst case scenario, it'll release on Febuary 7th. But I'll probably have it done by the end of the week. Let me know if there are any things you want to see fixed before the 1.0 release.
