### ISSUE TITLE
Make it easy to return something else from a cascade macro

### ISSUE THREAD

**Issue by snowsignal** [InquisitivePenguin/cascade#9]
Looking at the method chaining example from `basic_example.rs`:
```rust
let method_chain_example = cascade! {
    ch: Chain::blank();
    ..add(5).add(6).add(7);
    | let ch = ();
  };
```
`| let ch = ();` is ugly and unintuitive. Instead, if the last expression has no semicolon, we should simply return that value instead of the value being cascaded. For example:
```rust
cascade! {
  ch: Chain::blank();
  ..add(5).add(6).add(7);
  ()
}
```

**Comment by Lucretiel** [comment]
This doesn't seem like it's that much different than a simple block expression? For example:

```rust
cascade! {
    vec: Vec::new();
    ..push(1);
    ..push(2);
    ..push(3);
    | vec2: vec.clone();
    ..push(4);
}
```

Doesn't seem to me like much of an improvement over:

```rust
{
    let vec = cascade! {
        Vec::new();
        ..push(1);
        ..push(2);
        ..push(3);
    };

    cascade! {
        vec.clone();
        ..push(4);
    }
}
```

**Comment by snowsignal** [comment]
I think you might be misunderstanding the change. Usually, the value returned in a block expression is the last expression in the block. But right now, that throws an error in cascade. All this change does is allow an expression at the end of the cascade, which acts as the return value. It makes the cascade macro more closely represent block syntax. Previously, you would have to shadow the variable (re-declare the named value being cascaded as something else), which isn't intuitive.

Here's another example of where this might become useful (note: this takes into account the other changes I plan on making):
```rust
fn main() {
  // Run application
  cascade! {
    Application::new();
    ..setup(Window::new(600,800));
    loop {
      ..tick();
    }
    ()
  }
}
```

**Comment by Lucretiel** [comment]
Ah, you're completely right!
